// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmzgsRNqM9tbAhsU278eF5OGftPrFndkA',
    appId: '1:602052234309:web:ef6fa75bf7f41a7e65a72c',
    messagingSenderId: '602052234309',
    projectId: 'testflutterfcm-afb0d',
    authDomain: 'testflutterfcm-afb0d.firebaseapp.com',
    storageBucket: 'testflutterfcm-afb0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBxbuBB1Phs1Z4dnbHHsfZxJ8l-54cjI',
    appId: '1:602052234309:android:46f0c6ee0f991f6765a72c',
    messagingSenderId: '602052234309',
    projectId: 'testflutterfcm-afb0d',
    storageBucket: 'testflutterfcm-afb0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCaj-g21jHi_sPa7vt3fo2k2dv8xtfAc',
    appId: '1:602052234309:ios:8ddbf67f25cfaef465a72c',
    messagingSenderId: '602052234309',
    projectId: 'testflutterfcm-afb0d',
    storageBucket: 'testflutterfcm-afb0d.appspot.com',
    iosClientId: '602052234309-55po3iq2a8ho305qmahcefkivh2380a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCaj-g21jHi_sPa7vt3fo2k2dv8xtfAc',
    appId: '1:602052234309:ios:8ddbf67f25cfaef465a72c',
    messagingSenderId: '602052234309',
    projectId: 'testflutterfcm-afb0d',
    storageBucket: 'testflutterfcm-afb0d.appspot.com',
    iosClientId: '602052234309-55po3iq2a8ho305qmahcefkivh2380a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestFcm',
  );
}
